### ISSUE TITLE
Option `removeUnusedNamespaces` does not work as documented

### ISSUE THREAD

**Issue by codeworrior** [kristian/minify-xml#1]
- First of all, the implementation contains a typo. It [checks](https://github.com/kristian/minify-xml/blob/master/index.js#L63) for a non-empty array of `used` namespaces before removing the unused ones. I guess the intention was to check for `unused` to be non-empty.

    Fails to remove namespace 'n' from
    ```xml
    <a xmlns:n="..." />
    ```

- Second, the implementation only checks for namespaces that are used for elements, not for namespaces that are used for attributes. 

   Unintentionally removes namespace 'n' from 
   ```xml
    <a xmlns:n="..." n:attr="value" />
   ```
- last but not least, as the regexp based approach does not understand the structure of the XML, it cannot detected when a local namespace is unnecessary in a subtree, it can only decide globally.

   Does not remove 2nd declaration of namespace 'n' in
   ```xml
    <a>
        <b1 xmlns:n="...">
            <n:c/>
        </b1>
        <b2 xmlns:n="...">
        </b2>
    </a>
    ```
   This does not cause errors, but does not achieve the optimal reduction.

The 2nd issue is the most important one for our use case in UI5 as we have some special namespaces that are used only for attributes (e.g. for custom data).

**Comment by kristian** [comment]
Fixed the bugs with 197305a and version 2.0.1. I was well aware of the sub-tre limitation, therefore I mentioned that only namespaces are removed that are not used *anywhere* in the document. But i think it‘s a good idea to point this out even more clearly int he README.md at least, which I did. Thanks @codeworrior!
