### ISSUE TITLE
Flag for multiple output files

### ISSUE THREAD

**Issue by Chris2011** [kristian/minify-xml#10]
It would be great, if you can add a flag to add multiple input files and multiple output files. With my plugin https://github.com/Chris2011/minifierbeans it is possible to minify a whole folder with multiple files. The problem is that everytime it finds a file, it will call the CLI and I would like to refactor the code to just call the CLI onces like: minify-xml --in file1.xml file2.xml file3.xml --out file1.min.xml file2.min.xml file3.min.xml.

What do you think about it? I still have a workaround in my mind if you don't think, that this will fit into your package.

**Comment by kristian** [comment]
\*yoda voice\* Mhm, unsure about this one I am!

I don't recall many CLIs following that pattern / behaviour and (more importantly) I also think this could lead to different understandings of how the CLI options are treated, introducing some "hidden rules". E.g. the number of input / output files needs to match. If it doesn't match do I throw an error? Is it supposed to "merge" all input XML files into one output XML if only one output is given for many inputs? ...

I think leaving this option out keeps the CLI simple and allows for quite some optimization, e.g. when piping files in, or wanting to spawn multiple processes, for minifying multiple XML files at once. Last but not least, the CLI is named "minify-xml" not "minify-xml**s**", thus I would like to keep it at one XML file per run for now. :)

Hope it's fine for you, sticking with your workaround for this one. Have a great holiday season!

**Comment by Chris2011** [comment]
Thx for your opinion, I thought so :D. I also created a thread at the google closure compiler cli with quite the same result. Yeah, it seems legit to me will do the workaround instead. I see it at my direction to do that. Also, multi input is quite common but as mentioned, just for the input, the output will be one single file most the time concatinated.

Wish you the same, thx for this package :)

**Comment by kristian** [comment]
> thx for this package :)

Most welcome :)
