### ISSUE TITLE
Command line argument for adding extra content to the output file

### ISSUE THREAD

**Issue by Chris2011** [kristian/minify-xml#12]
My NetBeans plugin has a JEditorPane for smth called "Fixed header content". I would like to add such extra stuff to the output file automatically after minifying. The old Java APIs are not working with files, but with streams and they can add the stuff as a prepend textstream to the output stream. The CLIs like google closure compiler, postcss with cssnano and others are working, most of the time with input/output files. So I would like to ask, whether you can add a new CLI argument to add extra content to the output file.

So my case will be: minify-xml --input: my.xml --extra (or whatever) "comments or extra xml" --output: my.min.xml.

For sure I can handle this in an other way, but it would be easier to have such an argument. What do you think?

**Comment by kristian** [comment]
Hey @Chris2011, thanks for you continuous interest in my project.

What you are asking for is pretty similar to the feature request #10, that you filed a couple of months ago.

On this one however, I have a pretty clear opinion: `minify-xml` is no file concatination tool. There are standard Linux and Windows CLIs like `cat` which achieve the same, so there is absolutely no need to add this to the CLI and thus needing to code, test, support and maintain it, I am sorry.

**Comment by Chris2011** [comment]
Hey @kristian thx for the info :). It is not similar to the other request. Those are 2 both different features. The other one was about multiple output files, this is to add extra content to a outputed file. But maybe your opinion is similar to this feature request and I can accept it :)

**Comment by kristian** [comment]
Thanks @Chris2011, I appreciate it.

Generally I would like to keep `minify-xml` a tool which does exactly that. Adding more stuff to either the CLI or the tool itself, that is not that (like concatenating files, or adding extra content), is for tools that do that.

If I would want to add that, I would need to write tests for it and also explain _why_ this is part of a XML minifier in the first place... and thus I would rather keep them out.

As said, thanks for your continuous intestest in the project though!
