### ISSUE TITLE
Strangely slow performance on files with long strings

### ISSUE THREAD

**Issue by Syampuuh** [kristian/minify-xml#14]
Despite speedy performance on other much larger files, minify-xml has been completely halting its work when trying to process files that, as far as I can tell as their common distinguishing factor anyway, have long strings within tags.
This file took about 15 minutes to process: https://pastebin.com/G4fGQ9DB

This file was sitting for something like 40 minutes before I noticed the halted progress and cancelled it: https://pastebin.com/3XMpZciC

**Comment by kristian** [comment]
I just released v3.4.0 with [8345fbc](https://github.com/kristian/minify-xml/commit/8345fbc452c7995f7dd0dd60f1df531a42d17ccf) which should fix your issue. Thanks for reporting!
