### ISSUE TITLE
Node incompatible

### ISSUE THREAD

**Issue by davidbesteltunts** [kristian/minify-xml#17]
Hello, in the project I am using "node 16" and when I went to install the library it gave an incompatibility error requiring version ">= 18", can you tell me how dangerous it is for me to follow the installation even using node 16? 

Unfortunately I can't update the version to 18 at the moment, I joined the project in progress and I don't know how much it would affect.

Anyway thanks in advance for making the library available, making life easier for many developers out there 🙌.

**Comment by kristian** [comment]
Should be pretty safe from Node 12 upwards. I will test and provide a fix to the package.json tomorrow. Hope this helps. Good night / day, wherever you are.

**Comment by kristian** [comment]
You can leave this issue open, I will comment & close when I fixed the issue 👍

**Comment by kristian** [comment]
Published version 4.1.0 to NPM, reducing the minimum required Node version to >=16. Using <16 should be somewhat safe as well, except for the development (tests) and streaming part, where I used some functions introduced in NodeJS 16 for the first time.

**Comment by kristian** [comment]
Fixed with c7755539713c36957509ffa78d4acf197ca41c13 hope this helps! :)
