### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by sdavids** [kristian/minify-xml#19]
https://keepachangelog.com/en/1.0.0/

**Comment by kristian** [comment]
Would you expect to add a changelog starting with the next release, or for all releases in the past?

**Comment by kristian** [comment]
Fixed with 3af81865b76af62f49e4474e02368b3bfe78d3ed

**Comment by sdavids** [comment]
Thanks

**Comment by sdavids** [comment]
You might also want to create GitHub releases.

https://cli.github.com/manual/gh_release_create


The workflow is:

```shell
$ git tag -s -a v1.0.0 -m "v1.0.0"
$ git push origin v1.0.0

$ gh release create v1.0.0 -F CHANGELOG.md
```
