### ISSUE TITLE
minify-xml should not touch CDATA sections

### ISSUE THREAD

**Issue by codeworrior** [kristian/minify-xml#2]
As minify-xml does not analyze the XML structure of a document, it also processes the content of CDATA sections, which it shouldn't touch.

```xml
<api>
  <description>
<![CDATA[
<a 
     href = "https://github.com"
   target = "_blank"
 >
    **** Hello, world! ****
</a>
]]></description>
</api>
```

**Comment by kristian** [comment]
Fixed with 0c2d3c1 and version 2.0.2. Thanks @codeworrior!
