### ISSUE TITLE
Provide a silent mode

### ISSUE THREAD

**Issue by sdavids** [kristian/minify-xml#25]
Please provide a way to silence this log message:

https://github.com/kristian/minify-xml/blob/13b01632dabefcf10df6ba8709c55235758a7952/cli.js#L136-L138

Maybe this as well:

https://github.com/kristian/minify-xml/blob/13b01632dabefcf10df6ba8709c55235758a7952/cli.js#L149-L150

---

Maybe via `--silent` like a lot of other tools.

---

While you are at it you might want to change the first message to use `console.info` and the second to `console.warn`.

https://developer.mozilla.org/en-US/docs/Web/API/console/info_static
https://developer.mozilla.org/en-US/docs/Web/API/console/warn_static

https://nodejs.org/docs/latest-v16.x/api/console.html#consoleinfodata-args
https://nodejs.org/docs/latest-v16.x/api/console.html#consolewarndata-args

**Comment by sdavids** [comment]
Alternatively, be silent by default and add `--verbose`.

**Comment by kristian** [comment]
Good point. Done with https://github.com/kristian/minify-xml/commit/32070bf2fb80d32cbc9d59a974af194b88e3d3c4 and released with version 4.5.0. Thanks!
