### ISSUE TITLE
removeUnusedNamespaces fails to recognise used namespaces in attributes

### ISSUE THREAD

**Issue by RandomByte** [kristian/minify-xml#5]
Even after [yesterday's fix](https://github.com/kristian/minify-xml/issues/4), it seems that the [regular expression](https://github.com/kristian/minify-xml/blob/34099efe0656e7728bbf8721f5a75aa5b7b4c27f/index.js#L95) still fails to detect the usage of namespaces in attributes.

For example the `customData` namespace in `<smartTable:SmartTable id="employee_table" customData:p13nDialogSettings='{filter:{visible:false}}' />`.

Also see https://github.com/SAP/ui5-cli/issues/385

**Comment by kristian** [comment]
Fixed with 2.1.4, sorry for any inconvenience caused!
