### ISSUE TITLE
Add -o --output cli argument 

### ISSUE THREAD

**Issue by Chris2011** [kristian/minify-xml#6]
Hey, I will use this npm package in my Apache NetBeans plugin Minifierbeans: https://github.com/Chris2011/minifierbeans. For this, I need the CLI where I call it like this: minify-xml myxmlfile.xml -o newfile.min.xml.

So I need the -o --output argument which is also common in such minifier CLIs. I had a look into -h and just see the -i --in-place argument and nothing else.

**Comment by kristian** [comment]
Sure, let me see what I can do tomorrow!

**Comment by kristian** [comment]
Added with 3b45f7a12ebff764d59cdc69a3e78b9900a6b361 and version 2.3.0. Hope this helps!

**Comment by Chris2011** [comment]
Great thx, will test it :)

**Comment by Chris2011** [comment]
It is working just fine :). Thx.
