### ISSUE TITLE
Add options as CLI arguments

### ISSUE THREAD

**Issue by Chris2011** [kristian/minify-xml#7]
As far as I can see, the only CLI argument is -i --in-place. But all the options, that I can use in the config file, are needed as a separate cli argument.

example:
`minify-xml bla.xml --remove-comments=false`

**Comment by kristian** [comment]
Sure, also that one I can understand. Let me work on this tomorrow as well!

**Comment by kristian** [comment]
Added with ab55aa82172af6ad226ee56965a9c2ac666d05ef and version 2.3.1! Hope this helps.

**Comment by Chris2011** [comment]
Great thx, will test it :)

**Comment by Chris2011** [comment]
It seems to work thx.
