### ISSUE TITLE
Give error message, if flag is not correct

### ISSUE THREAD

**Issue by Chris2011** [kristian/minify-xml#9]
When I try an argument, which is not available normally the help will called again with the error like "Unknown `--my-flag`. Just an Idea. So I would expect, when I had a typo, what can happen with such long arguments like --remove-witespace-between-tags (h is missing here) I should get a hint, that this is an unknown flag.

**Comment by kristian** [comment]
Mhm, yes. I see that also as "good habbit". Unfortunately `meow` which is used for the CLI currently doesn't support this option yet, see: https://github.com/sindresorhus/meow/issues/126

Help wanted. Maybe I take a stab at it, if I find the time on the weekend though.

**Comment by Chris2011** [comment]
That's fine, I can live with that for now :). Thx for the information.

**Comment by kristian** [comment]
`meow` added an `allowUnknownFlags` option, which is now set w/ 2.5.0! Enjoy and thanks for the suggestion! 👍

**Comment by Chris2011** [comment]
Great thx :)
